-- Generated by Mocodo 4.3.3

CREATE TABLE CATEGORY (
  PRIMARY KEY (id_category),
  id_category INT NOT NULL,
  name        VARCHAR(150)
);

CREATE TABLE CONVERSATION (
  PRIMARY KEY (id_conversation),
  id_conversation INT NOT NULL,
  created_at      DATETIME,
  id_ticket       INT NOT NULL,
  UNIQUE (id_ticket)
);

CREATE TABLE MESSAGE (
  PRIMARY KEY (id_message),
  id_message      INT NOT NULL,
  content         TEXT,
  created_at      DATETIME,
  updated_at      DATETIME,
  id_conversation INT NOT NULL,
  id_user         INT NOT NULL
);

CREATE TABLE ROLE (
  PRIMARY KEY (id_role),
  id_role INT NOT NULL,
  name    VARCHAR(50)
);

CREATE TABLE SPECIALISER (
  PRIMARY KEY (id_user, id_category),
  id_user     INT NOT NULL,
  id_category INT NOT NULL
);

CREATE TABLE TICKET (
  PRIMARY KEY (id_ticket),
  id_ticket        INT NOT NULL,
  title            VARCHAR(150),
  description      TEXT,
  status           VARCHAR(50),
  priority         VARCHAR(50),
  created_at       DATETIME,
  updated_at       DATETIME,
  id_category      INT NOT NULL,
  id_user_agent    INT NULL,
  id_user_createur INT NOT NULL
);

CREATE TABLE USERS (
  PRIMARY KEY (id_user),
  id_user    INT NOT NULL,
  first_name VARCHAR(150),
  last_name  VARCHAR(150),
  email      VARCHAR(150),
  password   VARCHAR(255),
  created_at DATETIME,
  id_role    INT NOT NULL
);

ALTER TABLE CONVERSATION ADD FOREIGN KEY (id_ticket) REFERENCES TICKET (id_ticket);

ALTER TABLE MESSAGE ADD FOREIGN KEY (id_user) REFERENCES USERS (id_user);
ALTER TABLE MESSAGE ADD FOREIGN KEY (id_conversation) REFERENCES CONVERSATION (id_conversation);

ALTER TABLE SPECIALISER ADD FOREIGN KEY (id_category) REFERENCES CATEGORY (id_category);
ALTER TABLE SPECIALISER ADD FOREIGN KEY (id_user) REFERENCES USERS (id_user);

ALTER TABLE TICKET ADD FOREIGN KEY (id_user_createur) REFERENCES USERS (id_user);
ALTER TABLE TICKET ADD FOREIGN KEY (id_user_agent) REFERENCES USERS (id_user);
ALTER TABLE TICKET ADD FOREIGN KEY (id_category) REFERENCES CATEGORY (id_category);

ALTER TABLE USERS ADD FOREIGN KEY (id_role) REFERENCES ROLE (id_role);
